version: "3.9"
services:
  gossip-chat:
    build: .
    expose:
      - "8080"
      - "7946"
    ports:
      - "8080-8082:8080"
      - "7946-7948:7946"
    command: --http_port 8080 --gossip_port 7946 --cluster gossip-chat:7946